name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: wuoc4114/flask-authen:${{ github.sha }}

      - name: Update manifest in GitOps repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone "https://khanhquoc4114:${{ GITOPS_TOKEN }}@github.com/khanhquoc4114/flask-authen-manifest.git"
          cd flask-authen-manifest

          git checkout main

          sed -i "s|image: .*|image: wuoc4114/flask-authen:${{ github.sha }}|" deployment.yaml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -am "Update image tag to ${{ github.sha }}"
          git push origin main
