name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: wuoc4114/flask-authen-backend:${{ github.sha }}

      - name: Build & Push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: wuoc4114/flask-authen-frontend:${{ github.sha }}

      - name: Update manifest in GitOps repo
        run: |
          git clone "https://khanhquoc4114:${{ secrets.GITOPS_TOKEN }}@github.com/khanhquoc4114/flask-authen-manifest.git"
          cd flask-authen-manifest/k8s
          git checkout main

          # Update backend image
          sed -i "s|image: .*flask-authen-backend:.*|image: wuoc4114/flask-authen-backend:${{ github.sha }}|" backend-deployment.yaml

          # Update frontend image
          sed -i "s|image: .*flask-authen-frontend:.*|image: wuoc4114/flask-authen-frontend:${{ github.sha }}|" frontend-deployment.yaml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -am "Update images to backend:${{ github.sha }} and frontend:${{ github.sha }}"
          git push origin main